# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=b'', max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
    ]
