# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAcademicDetails',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('qualification', models.CharField(max_length=25, null=True, blank=True)),
                ('subjects', models.CharField(max_length=255, null=True, blank=True)),
                ('passingYear', models.SmallIntegerField(default=0)),
                ('institute', models.CharField(max_length=255, null=True, blank=True)),
                ('perOrGrade', models.CharField(max_length=25, null=True, blank=True)),
                ('certificateCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/certificate/%Y/%m/', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBankDetails',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bankAccount', models.CharField(max_length=25, null=True, blank=True)),
                ('bankName', models.CharField(max_length=100, null=True, blank=True)),
                ('ifscCode', models.CharField(max_length=25, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEmergencyContact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, null=True, blank=True)),
                ('relation', models.CharField(max_length=25, null=True, blank=True)),
                ('address1', models.CharField(max_length=255, null=True, blank=True)),
                ('address2', models.CharField(max_length=255, null=True, blank=True)),
                ('city', models.CharField(max_length=50, null=True, blank=True)),
                ('state', models.CharField(max_length=50, null=True, blank=True)),
                ('country', models.CharField(max_length=50, null=True, blank=True)),
                ('pin', models.CharField(max_length=20, null=True, blank=True)),
                ('mobile', models.CharField(max_length=100, null=True, blank=True)),
                ('phone', models.CharField(max_length=100, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExperienceDetails',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('company', models.CharField(max_length=255, null=True, blank=True)),
                ('address', models.CharField(max_length=255, null=True, blank=True)),
                ('designation', models.CharField(max_length=50, null=True, blank=True)),
                ('reportingTo', models.CharField(max_length=255, null=True, blank=True)),
                ('contactNumber', models.CharField(max_length=50, null=True, blank=True)),
                ('lastDrawnSalary', models.CharField(max_length=10, null=True, blank=True)),
                ('dateOfJoining', models.CharField(max_length=100, null=True, blank=True)),
                ('dateOfRelieving', models.CharField(max_length=100, null=True, blank=True)),
                ('totalTime', models.CharField(max_length=50, null=True, blank=True)),
                ('reasonForSeparation', models.CharField(max_length=255, null=True, blank=True)),
                ('paySlipCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/payslip/%Y/%m/', blank=True)),
                ('relievingCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/relieving/%Y/%m/', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFamilyDetails',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255, null=True, blank=True)),
                ('relation', models.CharField(max_length=25, null=True, blank=True)),
                ('fullAddress', models.TextField(max_length=255, null=True, blank=True)),
                ('mobile', models.CharField(max_length=100, null=True, blank=True)),
                ('phone', models.CharField(max_length=100, null=True, blank=True)),
                ('dateOfBirth', models.CharField(max_length=100, null=True, blank=True)),
                ('occupation', models.CharField(max_length=100, null=True, blank=True)),
                ('organisation', models.CharField(max_length=255, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeIDProof',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('aadharNumber', models.CharField(max_length=50, null=True, blank=True)),
                ('aadharCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/aadhar/%Y/%m/', blank=True)),
                ('panNumber', models.CharField(max_length=50, null=True, blank=True)),
                ('panCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/pan/%Y/%m/', blank=True)),
                ('dlNumber', models.CharField(max_length=50, null=True, blank=True)),
                ('dlCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/dl/%Y/%m/', blank=True)),
                ('passportNumber', models.CharField(max_length=50, null=True, blank=True)),
                ('passportCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/passport/%Y/%m/', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('empCode', models.CharField(db_index=True, max_length=10, null=True, blank=True)),
                ('reportToEmpCode', models.CharField(db_index=True, max_length=10, null=True, blank=True)),
                ('reportToEmpName', models.CharField(max_length=100, null=True, blank=True)),
                ('dateOfJoining', models.CharField(max_length=100, null=True, blank=True)),
                ('firstName', models.CharField(max_length=200, db_index=True)),
                ('middleName', models.CharField(max_length=100, null=True, blank=True)),
                ('lastName', models.CharField(db_index=True, max_length=100, null=True, blank=True)),
                ('gender', models.CharField(max_length=1, null=True, blank=True)),
                ('dateOfBirth', models.CharField(max_length=100, null=True, blank=True)),
                ('birthPlace', models.CharField(max_length=100, null=True, blank=True)),
                ('motherTongue', models.CharField(max_length=100, null=True, blank=True)),
                ('otherLanguages', models.CharField(max_length=200, null=True, blank=True)),
                ('stateDomicile', models.CharField(max_length=100, null=True, blank=True)),
                ('religion', models.CharField(max_length=100, null=True, blank=True)),
                ('maritalStatus', models.CharField(max_length=100, null=True, blank=True)),
                ('numberChildren', models.CharField(max_length=2, null=True, blank=True)),
                ('numberSiblings', models.CharField(max_length=2, null=True, blank=True)),
                ('bloodGroup', models.CharField(max_length=20, null=True, blank=True)),
                ('personalMobile', models.CharField(db_index=True, max_length=100, null=True, blank=True)),
                ('personalEmail', models.EmailField(db_index=True, max_length=255, null=True, blank=True)),
                ('userPhoto', models.ImageField(null=True, upload_to=b'static/private/employee/photos/%Y/%m/', blank=True)),
                ('signatureCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/signature/%Y/%m/', blank=True)),
                ('thumbImpressionCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/thumbimpression/%Y/%m/', blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('updatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('bandId', models.ForeignKey(blank=True, to='General.Band', null=True)),
                ('departmentId', models.ForeignKey(blank=True, to='General.Department', null=True)),
                ('designationId', models.ForeignKey(blank=True, to='General.Designation', null=True)),
                ('locationId', models.ForeignKey(blank=True, to='Location.Location', null=True)),
                ('reportToEmpId', models.ForeignKey(related_name='report_to', blank=True, to='Employee.EmployeeMaster', null=True)),
                ('roleId', models.ForeignKey(blank=True, to='General.Role', null=True)),
                ('updatedBy', models.ForeignKey(related_name='EmployeeMasterUpdatedByUser', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('userId', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeNomineeDetails',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('isDependent', models.BooleanField(default=False)),
                ('isPFNominee', models.BooleanField(default=False)),
                ('pfPercentage', models.SmallIntegerField(default=0)),
                ('isBFNominee', models.BooleanField(default=False)),
                ('bfPercentage', models.SmallIntegerField(default=0)),
                ('isGFNominee', models.BooleanField(default=False)),
                ('gfPercentage', models.SmallIntegerField(default=0)),
                ('isESICNominee', models.BooleanField(default=False)),
                ('esicPercentage', models.SmallIntegerField(default=0)),
                ('bankAccount', models.CharField(max_length=25, null=True, blank=True)),
                ('bankName', models.CharField(max_length=100, null=True, blank=True)),
                ('ifscCode', models.CharField(max_length=25, null=True, blank=True)),
                ('aadharNumber', models.CharField(max_length=50, null=True, blank=True)),
                ('aadharCopy', models.FileField(null=True, upload_to=b'static/private/employee/nominee/files/aadhar/%Y/%m/', blank=True)),
                ('residenceCopy', models.FileField(null=True, upload_to=b'static/private/employee/nominee/files/residence/%Y/%m/', blank=True)),
                ('photo', models.ImageField(null=True, upload_to=b'static/private/employee/nominee/files/photo/%Y/%m/', blank=True)),
                ('employeeId', models.ForeignKey(to='Employee.EmployeeMaster')),
                ('familyId', models.ForeignKey(to='Employee.EmployeeFamilyDetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePermanentAddress',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('address1', models.CharField(max_length=255, null=True, blank=True)),
                ('address2', models.CharField(max_length=255, null=True, blank=True)),
                ('city', models.CharField(max_length=50, null=True, blank=True)),
                ('state', models.CharField(max_length=50, null=True, blank=True)),
                ('country', models.CharField(max_length=50, null=True, blank=True)),
                ('pin', models.CharField(max_length=20, null=True, blank=True)),
                ('employeeId', models.ForeignKey(to='Employee.EmployeeMaster')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePresentAddress',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('address1', models.CharField(max_length=255, null=True, blank=True)),
                ('address2', models.CharField(max_length=255, null=True, blank=True)),
                ('city', models.CharField(max_length=50, null=True, blank=True)),
                ('state', models.CharField(max_length=50, null=True, blank=True)),
                ('country', models.CharField(max_length=50, null=True, blank=True)),
                ('pin', models.CharField(max_length=20, null=True, blank=True)),
                ('employeeId', models.ForeignKey(to='Employee.EmployeeMaster')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReferenceDetails',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fullName', models.CharField(max_length=255, null=True, blank=True)),
                ('fatherName', models.CharField(max_length=255, null=True, blank=True)),
                ('fullAddress', models.CharField(max_length=255, null=True, blank=True)),
                ('company', models.CharField(max_length=255, null=True, blank=True)),
                ('designation', models.CharField(max_length=50, null=True, blank=True)),
                ('officeAddress', models.CharField(max_length=255, null=True, blank=True)),
                ('phoneNumber', models.CharField(max_length=50, null=True, blank=True)),
                ('knownFromDate', models.CharField(max_length=100, null=True, blank=True)),
                ('idProofCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/reference/proof/%Y/%m/', blank=True)),
                ('signedLetterCopy', models.FileField(null=True, upload_to=b'static/private/employee/files/reference/letter/%Y/%m/', blank=True)),
                ('employeeId', models.ForeignKey(to='Employee.EmployeeMaster')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReferralDetails',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('referralEmpCode', models.CharField(db_index=True, max_length=10, null=True, blank=True)),
                ('employeeId', models.ForeignKey(to='Employee.EmployeeMaster')),
                ('referralId', models.ForeignKey(related_name='EmployeeReferralID', blank=True, to='Employee.EmployeeMaster', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSocialInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('facebook', models.CharField(max_length=255, null=True, blank=True)),
                ('linkedin', models.CharField(max_length=255, null=True, blank=True)),
                ('employeeId', models.ForeignKey(to='Employee.EmployeeMaster')),
            ],
        ),
        migrations.AddField(
            model_name='employeeidproof',
            name='employeeId',
            field=models.ForeignKey(to='Employee.EmployeeMaster'),
        ),
        migrations.AddField(
            model_name='employeefamilydetails',
            name='employeeId',
            field=models.ForeignKey(to='Employee.EmployeeMaster'),
        ),
        migrations.AddField(
            model_name='employeeexperiencedetails',
            name='employeeId',
            field=models.ForeignKey(to='Employee.EmployeeMaster'),
        ),
        migrations.AddField(
            model_name='employeeemergencycontact',
            name='employeeId',
            field=models.ForeignKey(to='Employee.EmployeeMaster'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='employeeId',
            field=models.ForeignKey(to='Employee.EmployeeMaster'),
        ),
        migrations.AddField(
            model_name='employeeacademicdetails',
            name='employeeId',
            field=models.ForeignKey(to='Employee.EmployeeMaster'),
        ),
    ]
